# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/aluno/tmig

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/aluno/tmig

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aluno/tmig/CMakeFiles /home/aluno/tmig//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aluno/tmig/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tmig

# Build rule for target.
tmig: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tmig
.PHONY : tmig

# fast build rule for target.
tmig/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tmig.dir/build.make CMakeFiles/tmig.dir/build
.PHONY : tmig/fast

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/build
.PHONY : tests/fast

external/glad/glad.o: external/glad/glad.c.o
.PHONY : external/glad/glad.o

# target to build an object file
external/glad/glad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tmig.dir/build.make CMakeFiles/tmig.dir/external/glad/glad.c.o
.PHONY : external/glad/glad.c.o

external/glad/glad.i: external/glad/glad.c.i
.PHONY : external/glad/glad.i

# target to preprocess a source file
external/glad/glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tmig.dir/build.make CMakeFiles/tmig.dir/external/glad/glad.c.i
.PHONY : external/glad/glad.c.i

external/glad/glad.s: external/glad/glad.c.s
.PHONY : external/glad/glad.s

# target to generate assembly for a file
external/glad/glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tmig.dir/build.make CMakeFiles/tmig.dir/external/glad/glad.c.s
.PHONY : external/glad/glad.c.s

external/stb/stb_image.o: external/stb/stb_image.c.o
.PHONY : external/stb/stb_image.o

# target to build an object file
external/stb/stb_image.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tmig.dir/build.make CMakeFiles/tmig.dir/external/stb/stb_image.c.o
.PHONY : external/stb/stb_image.c.o

external/stb/stb_image.i: external/stb/stb_image.c.i
.PHONY : external/stb/stb_image.i

# target to preprocess a source file
external/stb/stb_image.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tmig.dir/build.make CMakeFiles/tmig.dir/external/stb/stb_image.c.i
.PHONY : external/stb/stb_image.c.i

external/stb/stb_image.s: external/stb/stb_image.c.s
.PHONY : external/stb/stb_image.s

# target to generate assembly for a file
external/stb/stb_image.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tmig.dir/build.make CMakeFiles/tmig.dir/external/stb/stb_image.c.s
.PHONY : external/stb/stb_image.c.s

src/camera.o: src/camera.cpp.o
.PHONY : src/camera.o

# target to build an object file
src/camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tmig.dir/build.make CMakeFiles/tmig.dir/src/camera.cpp.o
.PHONY : src/camera.cpp.o

src/camera.i: src/camera.cpp.i
.PHONY : src/camera.i

# target to preprocess a source file
src/camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tmig.dir/build.make CMakeFiles/tmig.dir/src/camera.cpp.i
.PHONY : src/camera.cpp.i

src/camera.s: src/camera.cpp.s
.PHONY : src/camera.s

# target to generate assembly for a file
src/camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tmig.dir/build.make CMakeFiles/tmig.dir/src/camera.cpp.s
.PHONY : src/camera.cpp.s

src/entity.o: src/entity.cpp.o
.PHONY : src/entity.o

# target to build an object file
src/entity.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tmig.dir/build.make CMakeFiles/tmig.dir/src/entity.cpp.o
.PHONY : src/entity.cpp.o

src/entity.i: src/entity.cpp.i
.PHONY : src/entity.i

# target to preprocess a source file
src/entity.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tmig.dir/build.make CMakeFiles/tmig.dir/src/entity.cpp.i
.PHONY : src/entity.cpp.i

src/entity.s: src/entity.cpp.s
.PHONY : src/entity.s

# target to generate assembly for a file
src/entity.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tmig.dir/build.make CMakeFiles/tmig.dir/src/entity.cpp.s
.PHONY : src/entity.cpp.s

src/gl/ebo.o: src/gl/ebo.cpp.o
.PHONY : src/gl/ebo.o

# target to build an object file
src/gl/ebo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tmig.dir/build.make CMakeFiles/tmig.dir/src/gl/ebo.cpp.o
.PHONY : src/gl/ebo.cpp.o

src/gl/ebo.i: src/gl/ebo.cpp.i
.PHONY : src/gl/ebo.i

# target to preprocess a source file
src/gl/ebo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tmig.dir/build.make CMakeFiles/tmig.dir/src/gl/ebo.cpp.i
.PHONY : src/gl/ebo.cpp.i

src/gl/ebo.s: src/gl/ebo.cpp.s
.PHONY : src/gl/ebo.s

# target to generate assembly for a file
src/gl/ebo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tmig.dir/build.make CMakeFiles/tmig.dir/src/gl/ebo.cpp.s
.PHONY : src/gl/ebo.cpp.s

src/gl/shader.o: src/gl/shader.cpp.o
.PHONY : src/gl/shader.o

# target to build an object file
src/gl/shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tmig.dir/build.make CMakeFiles/tmig.dir/src/gl/shader.cpp.o
.PHONY : src/gl/shader.cpp.o

src/gl/shader.i: src/gl/shader.cpp.i
.PHONY : src/gl/shader.i

# target to preprocess a source file
src/gl/shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tmig.dir/build.make CMakeFiles/tmig.dir/src/gl/shader.cpp.i
.PHONY : src/gl/shader.cpp.i

src/gl/shader.s: src/gl/shader.cpp.s
.PHONY : src/gl/shader.s

# target to generate assembly for a file
src/gl/shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tmig.dir/build.make CMakeFiles/tmig.dir/src/gl/shader.cpp.s
.PHONY : src/gl/shader.cpp.s

src/gl/texture.o: src/gl/texture.cpp.o
.PHONY : src/gl/texture.o

# target to build an object file
src/gl/texture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tmig.dir/build.make CMakeFiles/tmig.dir/src/gl/texture.cpp.o
.PHONY : src/gl/texture.cpp.o

src/gl/texture.i: src/gl/texture.cpp.i
.PHONY : src/gl/texture.i

# target to preprocess a source file
src/gl/texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tmig.dir/build.make CMakeFiles/tmig.dir/src/gl/texture.cpp.i
.PHONY : src/gl/texture.cpp.i

src/gl/texture.s: src/gl/texture.cpp.s
.PHONY : src/gl/texture.s

# target to generate assembly for a file
src/gl/texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tmig.dir/build.make CMakeFiles/tmig.dir/src/gl/texture.cpp.s
.PHONY : src/gl/texture.cpp.s

src/gl/vao.o: src/gl/vao.cpp.o
.PHONY : src/gl/vao.o

# target to build an object file
src/gl/vao.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tmig.dir/build.make CMakeFiles/tmig.dir/src/gl/vao.cpp.o
.PHONY : src/gl/vao.cpp.o

src/gl/vao.i: src/gl/vao.cpp.i
.PHONY : src/gl/vao.i

# target to preprocess a source file
src/gl/vao.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tmig.dir/build.make CMakeFiles/tmig.dir/src/gl/vao.cpp.i
.PHONY : src/gl/vao.cpp.i

src/gl/vao.s: src/gl/vao.cpp.s
.PHONY : src/gl/vao.s

# target to generate assembly for a file
src/gl/vao.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tmig.dir/build.make CMakeFiles/tmig.dir/src/gl/vao.cpp.s
.PHONY : src/gl/vao.cpp.s

src/gl/vbo.o: src/gl/vbo.cpp.o
.PHONY : src/gl/vbo.o

# target to build an object file
src/gl/vbo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tmig.dir/build.make CMakeFiles/tmig.dir/src/gl/vbo.cpp.o
.PHONY : src/gl/vbo.cpp.o

src/gl/vbo.i: src/gl/vbo.cpp.i
.PHONY : src/gl/vbo.i

# target to preprocess a source file
src/gl/vbo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tmig.dir/build.make CMakeFiles/tmig.dir/src/gl/vbo.cpp.i
.PHONY : src/gl/vbo.cpp.i

src/gl/vbo.s: src/gl/vbo.cpp.s
.PHONY : src/gl/vbo.s

# target to generate assembly for a file
src/gl/vbo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tmig.dir/build.make CMakeFiles/tmig.dir/src/gl/vbo.cpp.s
.PHONY : src/gl/vbo.cpp.s

src/mesh.o: src/mesh.cpp.o
.PHONY : src/mesh.o

# target to build an object file
src/mesh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tmig.dir/build.make CMakeFiles/tmig.dir/src/mesh.cpp.o
.PHONY : src/mesh.cpp.o

src/mesh.i: src/mesh.cpp.i
.PHONY : src/mesh.i

# target to preprocess a source file
src/mesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tmig.dir/build.make CMakeFiles/tmig.dir/src/mesh.cpp.i
.PHONY : src/mesh.cpp.i

src/mesh.s: src/mesh.cpp.s
.PHONY : src/mesh.s

# target to generate assembly for a file
src/mesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tmig.dir/build.make CMakeFiles/tmig.dir/src/mesh.cpp.s
.PHONY : src/mesh.cpp.s

src/window.o: src/window.cpp.o
.PHONY : src/window.o

# target to build an object file
src/window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tmig.dir/build.make CMakeFiles/tmig.dir/src/window.cpp.o
.PHONY : src/window.cpp.o

src/window.i: src/window.cpp.i
.PHONY : src/window.i

# target to preprocess a source file
src/window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tmig.dir/build.make CMakeFiles/tmig.dir/src/window.cpp.i
.PHONY : src/window.cpp.i

src/window.s: src/window.cpp.s
.PHONY : src/window.s

# target to generate assembly for a file
src/window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tmig.dir/build.make CMakeFiles/tmig.dir/src/window.cpp.s
.PHONY : src/window.cpp.s

tests/main.o: tests/main.cpp.o
.PHONY : tests/main.o

# target to build an object file
tests/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/main.cpp.o
.PHONY : tests/main.cpp.o

tests/main.i: tests/main.cpp.i
.PHONY : tests/main.i

# target to preprocess a source file
tests/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/main.cpp.i
.PHONY : tests/main.cpp.i

tests/main.s: tests/main.cpp.s
.PHONY : tests/main.s

# target to generate assembly for a file
tests/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/main.cpp.s
.PHONY : tests/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... tests"
	@echo "... tmig"
	@echo "... external/glad/glad.o"
	@echo "... external/glad/glad.i"
	@echo "... external/glad/glad.s"
	@echo "... external/stb/stb_image.o"
	@echo "... external/stb/stb_image.i"
	@echo "... external/stb/stb_image.s"
	@echo "... src/camera.o"
	@echo "... src/camera.i"
	@echo "... src/camera.s"
	@echo "... src/entity.o"
	@echo "... src/entity.i"
	@echo "... src/entity.s"
	@echo "... src/gl/ebo.o"
	@echo "... src/gl/ebo.i"
	@echo "... src/gl/ebo.s"
	@echo "... src/gl/shader.o"
	@echo "... src/gl/shader.i"
	@echo "... src/gl/shader.s"
	@echo "... src/gl/texture.o"
	@echo "... src/gl/texture.i"
	@echo "... src/gl/texture.s"
	@echo "... src/gl/vao.o"
	@echo "... src/gl/vao.i"
	@echo "... src/gl/vao.s"
	@echo "... src/gl/vbo.o"
	@echo "... src/gl/vbo.i"
	@echo "... src/gl/vbo.s"
	@echo "... src/mesh.o"
	@echo "... src/mesh.i"
	@echo "... src/mesh.s"
	@echo "... src/window.o"
	@echo "... src/window.i"
	@echo "... src/window.s"
	@echo "... tests/main.o"
	@echo "... tests/main.i"
	@echo "... tests/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

